version: '1.0'

# documentation: https://kinsta.com/blog/docker-compose-volumes/
volumes:
    ros2_ws:
      driver: local
      driver_opts:
        type: none
        device: ../../ros2_ws
        o: bind

services:
  ros2:
    build: .
    volumes:
      - ros2_ws:/root/ros2_ws
    tty: true